package borg.ed.cruisecontrol;

public enum GameState {

	UNKNOWN,
	COMPASS_ALIGNING_JUMP,
	COMPASS_ALIGNED_JUMP,
	JUMPING,
	HONK_AND_SELECT,
	COMPASS_ALIGNING_STAR,
	COMPASS_ALIGNED_STAR,
	COMPASS_ALIGNING_ESCAPE,
	COMPASS_ALIGNED_ESCAPE;

}
